from pack import generate_pack
import pytest


def test_generate_pack():
    pack = generate_pack(3)
    assert len(pack) == 7
    pack = generate_pack(4)
    assert len(pack) == 13
    pack = generate_pack(5)
    assert len(pack) == 21
    pack = generate_pack(6)
    assert len(pack) == 31
    pack = generate_pack(8)
    assert len(pack) == 57


def test_generate_pack_below_3():
    with pytest.raises(ValueError):
        generate_pack(2)


def test_generate_pack_over_8():
    with pytest.raises(ValueError):
        generate_pack(9)


def test_generate_pack_8_symbols():
    pack = generate_pack(8)
    assert pack == [
        ["jeden", "dwa", "trzy", "cztery", "pięć", "sześć", "siedem", "osiem"],
        [
            "jeden",
            "dziewięć",
            "dziesięć",
            "jedenaście",
            "dwanaście",
            "trzynaście",
            "czternaście",
            "piętnaście",
        ],
        [
            "jeden",
            "szesnaście",
            "siedemnaście",
            "osiemnaście",
            "dziewiętnaście",
            "dwadzieścia",
            "dwadzieścia jeden",
            "dwadzieścia dwa",
        ],
        [
            "jeden",
            "dwadzieścia trzy",
            "dwadzieścia cztery",
            "dwadzieścia pięć",
            "dwadzieścia sześć",
            "dwadzieścia siedem",
            "dwadzieścia osiem",
            "dwadzieścia dziewięć",
        ],
        [
            "jeden",
            "trzydzieści",
            "trzydzieści jeden",
            "trzydzieści dwa",
            "trzydzieści trzy",
            "trzydzieści cztery",
            "trzydzieści pięć",
            "trzydzieści sześć",
        ],
        [
            "jeden",
            "trzydzieści siedem",
            "trzydzieści osiem",
            "trzydzieści dziewięć",
            "czterdzieści",
            "czterdzieści jeden",
            "czterdzieści dwa",
            "czterdzieści trzy",
        ],
        [
            "jeden",
            "czterdzieści cztery",
            "czterdzieści pięć",
            "czterdzieści sześć",
            "czterdzieści siedem",
            "czterdzieści osiem",
            "czterdzieści dziewięć",
            "pięćdziesiąt",
        ],
        [
            "jeden",
            "pięćdziesiąt jeden",
            "pięćdziesiąt dwa",
            "pięćdziesiąt trzy",
            "pięćdziesiąt cztery",
            "pięćdziesiąt pięć",
            "pięćdziesiąt sześć",
            "pięćdziesiąt siedem",
        ],
        [
            "dwa",
            "dziewięć",
            "szesnaście",
            "dwadzieścia trzy",
            "trzydzieści",
            "trzydzieści siedem",
            "czterdzieści cztery",
            "pięćdziesiąt jeden",
        ],
        [
            "dwa",
            "dziesięć",
            "siedemnaście",
            "dwadzieścia cztery",
            "trzydzieści jeden",
            "trzydzieści osiem",
            "czterdzieści pięć",
            "pięćdziesiąt dwa",
        ],
        [
            "dwa",
            "jedenaście",
            "osiemnaście",
            "dwadzieścia pięć",
            "trzydzieści dwa",
            "trzydzieści dziewięć",
            "czterdzieści sześć",
            "pięćdziesiąt trzy",
        ],
        [
            "dwa",
            "dwanaście",
            "dziewiętnaście",
            "dwadzieścia sześć",
            "trzydzieści trzy",
            "czterdzieści",
            "czterdzieści siedem",
            "pięćdziesiąt cztery",
        ],
        [
            "dwa",
            "trzynaście",
            "dwadzieścia",
            "dwadzieścia siedem",
            "trzydzieści cztery",
            "czterdzieści jeden",
            "czterdzieści osiem",
            "pięćdziesiąt pięć",
        ],
        [
            "dwa",
            "czternaście",
            "dwadzieścia jeden",
            "dwadzieścia osiem",
            "trzydzieści pięć",
            "czterdzieści dwa",
            "czterdzieści dziewięć",
            "pięćdziesiąt sześć",
        ],
        [
            "dwa",
            "piętnaście",
            "dwadzieścia dwa",
            "dwadzieścia dziewięć",
            "trzydzieści sześć",
            "czterdzieści trzy",
            "pięćdziesiąt",
            "pięćdziesiąt siedem",
        ],
        [
            "trzy",
            "dziewięć",
            "siedemnaście",
            "dwadzieścia pięć",
            "trzydzieści trzy",
            "czterdzieści jeden",
            "czterdzieści dziewięć",
            "pięćdziesiąt siedem",
        ],
        [
            "trzy",
            "dziesięć",
            "osiemnaście",
            "dwadzieścia sześć",
            "trzydzieści cztery",
            "czterdzieści dwa",
            "pięćdziesiąt",
            "pięćdziesiąt jeden",
        ],
        [
            "trzy",
            "jedenaście",
            "dziewiętnaście",
            "dwadzieścia siedem",
            "trzydzieści pięć",
            "czterdzieści trzy",
            "czterdzieści cztery",
            "pięćdziesiąt dwa",
        ],
        [
            "trzy",
            "dwanaście",
            "dwadzieścia",
            "dwadzieścia osiem",
            "trzydzieści sześć",
            "trzydzieści siedem",
            "czterdzieści pięć",
            "pięćdziesiąt trzy",
        ],
        [
            "trzy",
            "trzynaście",
            "dwadzieścia jeden",
            "dwadzieścia dziewięć",
            "trzydzieści",
            "trzydzieści osiem",
            "czterdzieści sześć",
            "pięćdziesiąt cztery",
        ],
        [
            "trzy",
            "czternaście",
            "dwadzieścia dwa",
            "dwadzieścia trzy",
            "trzydzieści jeden",
            "trzydzieści dziewięć",
            "czterdzieści siedem",
            "pięćdziesiąt pięć",
        ],
        [
            "trzy",
            "piętnaście",
            "szesnaście",
            "dwadzieścia cztery",
            "trzydzieści dwa",
            "czterdzieści",
            "czterdzieści osiem",
            "pięćdziesiąt sześć",
        ],
        [
            "cztery",
            "dziewięć",
            "osiemnaście",
            "dwadzieścia siedem",
            "trzydzieści sześć",
            "trzydzieści osiem",
            "czterdzieści siedem",
            "pięćdziesiąt sześć",
        ],
        [
            "cztery",
            "dziesięć",
            "dziewiętnaście",
            "dwadzieścia osiem",
            "trzydzieści",
            "trzydzieści dziewięć",
            "czterdzieści osiem",
            "pięćdziesiąt siedem",
        ],
        [
            "cztery",
            "jedenaście",
            "dwadzieścia",
            "dwadzieścia dziewięć",
            "trzydzieści jeden",
            "czterdzieści",
            "czterdzieści dziewięć",
            "pięćdziesiąt jeden",
        ],
        [
            "cztery",
            "dwanaście",
            "dwadzieścia jeden",
            "dwadzieścia trzy",
            "trzydzieści dwa",
            "czterdzieści jeden",
            "pięćdziesiąt",
            "pięćdziesiąt dwa",
        ],
        [
            "cztery",
            "trzynaście",
            "dwadzieścia dwa",
            "dwadzieścia cztery",
            "trzydzieści trzy",
            "czterdzieści dwa",
            "czterdzieści cztery",
            "pięćdziesiąt trzy",
        ],
        [
            "cztery",
            "czternaście",
            "szesnaście",
            "dwadzieścia pięć",
            "trzydzieści cztery",
            "czterdzieści trzy",
            "czterdzieści pięć",
            "pięćdziesiąt cztery",
        ],
        [
            "cztery",
            "piętnaście",
            "siedemnaście",
            "dwadzieścia sześć",
            "trzydzieści pięć",
            "trzydzieści siedem",
            "czterdzieści sześć",
            "pięćdziesiąt pięć",
        ],
        [
            "pięć",
            "dziewięć",
            "dziewiętnaście",
            "dwadzieścia dziewięć",
            "trzydzieści dwa",
            "czterdzieści dwa",
            "czterdzieści pięć",
            "pięćdziesiąt pięć",
        ],
        [
            "pięć",
            "dziesięć",
            "dwadzieścia",
            "dwadzieścia trzy",
            "trzydzieści trzy",
            "czterdzieści trzy",
            "czterdzieści sześć",
            "pięćdziesiąt sześć",
        ],
        [
            "pięć",
            "jedenaście",
            "dwadzieścia jeden",
            "dwadzieścia cztery",
            "trzydzieści cztery",
            "trzydzieści siedem",
            "czterdzieści siedem",
            "pięćdziesiąt siedem",
        ],
        [
            "pięć",
            "dwanaście",
            "dwadzieścia dwa",
            "dwadzieścia pięć",
            "trzydzieści pięć",
            "trzydzieści osiem",
            "czterdzieści osiem",
            "pięćdziesiąt jeden",
        ],
        [
            "pięć",
            "trzynaście",
            "szesnaście",
            "dwadzieścia sześć",
            "trzydzieści sześć",
            "trzydzieści dziewięć",
            "czterdzieści dziewięć",
            "pięćdziesiąt dwa",
        ],
        [
            "pięć",
            "czternaście",
            "siedemnaście",
            "dwadzieścia siedem",
            "trzydzieści",
            "czterdzieści",
            "pięćdziesiąt",
            "pięćdziesiąt trzy",
        ],
        [
            "pięć",
            "piętnaście",
            "osiemnaście",
            "dwadzieścia osiem",
            "trzydzieści jeden",
            "czterdzieści jeden",
            "czterdzieści cztery",
            "pięćdziesiąt cztery",
        ],
        [
            "sześć",
            "dziewięć",
            "dwadzieścia",
            "dwadzieścia cztery",
            "trzydzieści pięć",
            "trzydzieści dziewięć",
            "pięćdziesiąt",
            "pięćdziesiąt cztery",
        ],
        [
            "sześć",
            "dziesięć",
            "dwadzieścia jeden",
            "dwadzieścia pięć",
            "trzydzieści sześć",
            "czterdzieści",
            "czterdzieści cztery",
            "pięćdziesiąt pięć",
        ],
        [
            "sześć",
            "jedenaście",
            "dwadzieścia dwa",
            "dwadzieścia sześć",
            "trzydzieści",
            "czterdzieści jeden",
            "czterdzieści pięć",
            "pięćdziesiąt sześć",
        ],
        [
            "sześć",
            "dwanaście",
            "szesnaście",
            "dwadzieścia siedem",
            "trzydzieści jeden",
            "czterdzieści dwa",
            "czterdzieści sześć",
            "pięćdziesiąt siedem",
        ],
        [
            "sześć",
            "trzynaście",
            "siedemnaście",
            "dwadzieścia osiem",
            "trzydzieści dwa",
            "czterdzieści trzy",
            "czterdzieści siedem",
            "pięćdziesiąt jeden",
        ],
        [
            "sześć",
            "czternaście",
            "osiemnaście",
            "dwadzieścia dziewięć",
            "trzydzieści trzy",
            "trzydzieści siedem",
            "czterdzieści osiem",
            "pięćdziesiąt dwa",
        ],
        [
            "sześć",
            "piętnaście",
            "dziewiętnaście",
            "dwadzieścia trzy",
            "trzydzieści cztery",
            "trzydzieści osiem",
            "czterdzieści dziewięć",
            "pięćdziesiąt trzy",
        ],
        [
            "siedem",
            "dziewięć",
            "dwadzieścia jeden",
            "dwadzieścia sześć",
            "trzydzieści jeden",
            "czterdzieści trzy",
            "czterdzieści osiem",
            "pięćdziesiąt trzy",
        ],
        [
            "siedem",
            "dziesięć",
            "dwadzieścia dwa",
            "dwadzieścia siedem",
            "trzydzieści dwa",
            "trzydzieści siedem",
            "czterdzieści dziewięć",
            "pięćdziesiąt cztery",
        ],
        [
            "siedem",
            "jedenaście",
            "szesnaście",
            "dwadzieścia osiem",
            "trzydzieści trzy",
            "trzydzieści osiem",
            "pięćdziesiąt",
            "pięćdziesiąt pięć",
        ],
        [
            "siedem",
            "dwanaście",
            "siedemnaście",
            "dwadzieścia dziewięć",
            "trzydzieści cztery",
            "trzydzieści dziewięć",
            "czterdzieści cztery",
            "pięćdziesiąt sześć",
        ],
        [
            "siedem",
            "trzynaście",
            "osiemnaście",
            "dwadzieścia trzy",
            "trzydzieści pięć",
            "czterdzieści",
            "czterdzieści pięć",
            "pięćdziesiąt siedem",
        ],
        [
            "siedem",
            "czternaście",
            "dziewiętnaście",
            "dwadzieścia cztery",
            "trzydzieści sześć",
            "czterdzieści jeden",
            "czterdzieści sześć",
            "pięćdziesiąt jeden",
        ],
        [
            "siedem",
            "piętnaście",
            "dwadzieścia",
            "dwadzieścia pięć",
            "trzydzieści",
            "czterdzieści dwa",
            "czterdzieści siedem",
            "pięćdziesiąt dwa",
        ],
        [
            "osiem",
            "dziewięć",
            "dwadzieścia dwa",
            "dwadzieścia osiem",
            "trzydzieści cztery",
            "czterdzieści",
            "czterdzieści sześć",
            "pięćdziesiąt dwa",
        ],
        [
            "osiem",
            "dziesięć",
            "szesnaście",
            "dwadzieścia dziewięć",
            "trzydzieści pięć",
            "czterdzieści jeden",
            "czterdzieści siedem",
            "pięćdziesiąt trzy",
        ],
        [
            "osiem",
            "jedenaście",
            "siedemnaście",
            "dwadzieścia trzy",
            "trzydzieści sześć",
            "czterdzieści dwa",
            "czterdzieści osiem",
            "pięćdziesiąt cztery",
        ],
        [
            "osiem",
            "dwanaście",
            "osiemnaście",
            "dwadzieścia cztery",
            "trzydzieści",
            "czterdzieści trzy",
            "czterdzieści dziewięć",
            "pięćdziesiąt pięć",
        ],
        [
            "osiem",
            "trzynaście",
            "dziewiętnaście",
            "dwadzieścia pięć",
            "trzydzieści jeden",
            "trzydzieści siedem",
            "pięćdziesiąt",
            "pięćdziesiąt sześć",
        ],
        [
            "osiem",
            "czternaście",
            "dwadzieścia",
            "dwadzieścia sześć",
            "trzydzieści dwa",
            "trzydzieści osiem",
            "czterdzieści cztery",
            "pięćdziesiąt siedem",
        ],
        [
            "osiem",
            "piętnaście",
            "dwadzieścia jeden",
            "dwadzieścia siedem",
            "trzydzieści trzy",
            "trzydzieści dziewięć",
            "czterdzieści pięć",
            "pięćdziesiąt jeden",
        ],
    ]
